//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCATPMVCMaintenance.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BCATPEntities : DbContext
    {
        public BCATPEntities()
            : base("name=BCATPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<airforce> airforces { get; set; }
        public virtual DbSet<midcanada> midcanada { get; set; }
        public virtual DbSet<army> armies { get; set; }
        public virtual DbSet<bcatp> bcatps { get; set; }
        public virtual DbSet<defunct> defuncts { get; set; }
        public virtual DbSet<dewline> dewlines { get; set; }
        public virtual DbSet<navy> navies { get; set; }
        public virtual DbSet<pinetree> pinetrees { get; set; }
    }
}
