//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCATPMVCMaintenance.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BCATPEntities : DbContext
    {
        public BCATPEntities()
            : base("name=BCATPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BCATPData> BCATPDatas { get; set; }

        public System.Data.Entity.DbSet<BCATPMVCMaintenance.Models.DewLineData> DewLineDatas { get; set; }

        public System.Data.Entity.DbSet<BCATPMVCMaintenance.Models.PinetreeData> PinetreeDatas { get; set; }
    }
}
